const employees = [
	{
		id: 1,
		name: 'Benyamin Gilbeart',
		position: 'Web Designer III',
		email: 'bgilbeart0@bravesites.com',
		salary: 164740,
	},
	{
		id: 2,
		name: 'Averil Pepineaux',
		position: 'Web Designer III',
		email: 'apepineaux1@liveinternet.ru',
		salary: 240001,
	},
	{
		id: 3,
		name: 'Cristionna Gracewood',
		position: 'Legal Assistant',
		email: 'cgracewood2@digg.com',
		salary: 254557,
	},
	{
		id: 4,
		name: 'Lammond Perceval',
		position: 'Associate Professor',
		email: 'lperceval3@fda.gov',
		salary: 356958,
	},
	{
		id: 5,
		name: 'Joannes Lightbowne',
		position: 'Accounting Assistant III',
		email: 'jlightbowne4@nih.gov',
		salary: 389442,
	},
	{
		id: 6,
		name: 'Tarrah Scemp',
		position: 'Staff Scientist',
		email: 'tscemp5@livejournal.com',
		salary: 312435,
	},
	{
		id: 7,
		name: 'Natty Mynott',
		position: 'Community Outreach Specialist',
		email: 'nmynott6@hud.gov',
		salary: 387494,
	},
	{
		id: 8,
		name: 'Hamilton Rheubottom',
		position: 'VP Product Management',
		email: 'hrheubottom7@nsw.gov.au',
		salary: 365309,
	},
	{
		id: 9,
		name: 'Parry Hryniewicz',
		position: 'Marketing Assistant',
		email: 'phryniewicz8@comcast.net',
		salary: 210702,
	},
	{
		id: 10,
		name: 'Verne Riseley',
		position: 'Geologist I',
		email: 'vriseley9@java.com',
		salary: 384305,
	},
	{
		id: 11,
		name: 'Omero Monkman',
		position: 'Nurse',
		email: 'omonkmana@behance.net',
		salary: 389868,
	},
	{
		id: 12,
		name: 'Silvie Genge',
		position: 'Office Assistant IV',
		email: 'sgengeb@ucla.edu',
		salary: 321017,
	},
	{
		id: 13,
		name: 'Madison Negus',
		position: 'Civil Engineer',
		email: 'mnegusc@icio.us',
		salary: 268364,
	},
	{
		id: 14,
		name: 'Hayyim McCorry',
		position: 'Senior Developer',
		email: 'hmccorryd@meetup.com',
		salary: 191440,
	},
	{
		id: 15,
		name: 'Lorant Mallinar',
		position: 'Structural Analysis Engineer',
		email: 'lmallinare@nationalgeographic.com',
		salary: 338608,
	},
	{
		id: 16,
		name: 'Carine Leyburn',
		position: 'Analog Circuit Design manager',
		email: 'cleyburnf@chicagotribune.com',
		salary: 407675,
	},
	{
		id: 17,
		name: 'Donnell Simonaitis',
		position: 'Associate Professor',
		email: 'dsimonaitisg@bizjournals.com',
		salary: 359661,
	},
	{
		id: 18,
		name: 'Rivi Sitford',
		position: 'Dental Hygienist',
		email: 'rsitfordh@ask.com',
		salary: 155692,
	},
	{
		id: 19,
		name: 'Wilbert Delhanty',
		position: 'Internal Auditor',
		email: 'wdelhantyi@newyorker.com',
		salary: 277708,
	},
	{
		id: 20,
		name: 'Alexander Assaf',
		position: 'Recruiting Manager',
		email: 'aassafj@sun.com',
		salary: 187046,
	},
	{
		id: 21,
		name: 'Hillery Blythin',
		position: 'Environmental Specialist',
		email: 'hblythink@upenn.edu',
		salary: 390302,
	},
	{
		id: 22,
		name: 'Ennis Tyrrell',
		position: 'Food Chemist',
		email: 'etyrrelll@abc.net.au',
		salary: 214585,
	},
	{
		id: 23,
		name: 'Stan Rittmeyer',
		position: 'Clinical Specialist',
		email: 'srittmeyerm@edublogs.org',
		salary: 206721,
	},
	{
		id: 24,
		name: 'Rollin Nolte',
		position: 'Developer III',
		email: 'rnolten@linkedin.com',
		salary: 300147,
	},
	{
		id: 25,
		name: 'Kiley Eadington',
		position: 'Teacher',
		email: 'keadingtono@theguardian.com',
		salary: 225094,
	},
	{
		id: 26,
		name: 'Peria Dunkersley',
		position: 'Civil Engineer',
		email: 'pdunkersleyp@blogtalkradio.com',
		salary: 332891,
	},
	{
		id: 27,
		name: 'Anallese Ruppert',
		position: 'Assistant Media Planner',
		email: 'aruppertq@is.gd',
		salary: 384855,
	},
	{
		id: 28,
		name: 'Berton Moring',
		position: 'Safety Technician IV',
		email: 'bmoringr@networkadvertising.org',
		salary: 151022,
	},
	{
		id: 29,
		name: 'Cary Woltering',
		position: 'Software Engineer II',
		email: 'cwolterings@slate.com',
		salary: 313658,
	},
	{
		id: 30,
		name: 'Camella MacColm',
		position: 'Automation Specialist III',
		email: 'cmaccolmt@tumblr.com',
		salary: 397794,
	},
];

export default employees;
